### ISSUE TITLE
Get Authorization Duration

### ISSUE THREAD

**Issue by manhhung1511** [nVuln/tiktokshop-php#12]
![image](https://user-images.githubusercontent.com/77888841/221869353-c141d41d-9e9a-4fa2-9757-5f5d8171cf50.png)
Hi. Help me! How to get authorization duration selected by user ? Thank you very much

**Comment by manhhung1511** [comment]
@nVuln help me

**Comment by nVuln** [comment]
please go to tiktokshop partner and send them a ticket support, they have best answer for your question
this is not my problem so I can't help, thanks
