### ISSUE TITLE
Validation upload image with SplFileInfo

### ISSUE THREAD

**Issue by febrihidayan** [nVuln/tiktokshop-php#2]
after updating your code i find it very annoying if i use image link. but it works great if it is omitted
```php
$img_data = file_get_contents($image);
```

https://github.com/nVuln/tiktokshop-php/blob/d8621d260ea065e4bed5471767c00867624c1e21/src/Resources/Product.php#L40

ref image: https://images.pexels.com/photos/206359/pexels-photo-206359.jpeg

**Comment by febrihidayan** [comment]
@nVuln you can also see api updates https://partner.tiktokshop.com/doc/page/262783#Request%20Parameters

**Comment by nVuln** [comment]
is their `img_data` param allowed image URL as input ?

**Comment by nVuln** [comment]
I just looked into api document and I don't see anything about this
<img width="795" alt="Screenshot 2022-12-07 at 4 49 15 PM" src="https://user-images.githubusercontent.com/54855446/206145788-b06618e3-a25f-4956-a1c7-a59ac83723b0.png">

btw, thanks for your information, let me try it

**Comment by febrihidayan** [comment]
okey, thanks too

**Comment by nVuln** [comment]
@febrihidayan I just tested it, param `img_data` not allowed url, always got error `upload file is invalid`
could you re-produce how to upload image by using url ?

**Comment by febrihidayan** [comment]
i did it like this and it worked
![image](https://user-images.githubusercontent.com/42211742/206241811-b873a4b1-26b4-47f6-be57-286f84a19329.png)

**Comment by febrihidayan** [comment]
or you can try it like this
![image](https://user-images.githubusercontent.com/42211742/206244302-86bde499-6223-4931-8f81-4f2c43c0d001.png)

**Comment by nVuln** [comment]
@febrihidayan that mean we handled image URL on our backend, tiktokshop api not handled it
let see what I can do to support it, thanks for your information

**Comment by manhhung1511** [comment]
Hi, I need your support. I create product and need these 2 parameters. Do you know where I can get it? Thank you very much
![image](https://user-images.githubusercontent.com/77888841/206472356-0afe4d4f-6449-4d92-adc3-51fe81154d01.png)

**Comment by nVuln** [comment]
@manhhung1511 next time please create new issue
for your question: I never used that params before, it's not required, but if you need it, you can try API `Get Product Attributes` with `attribute_type = SALES_PROPERTY`
api detail here: https://partner.tiktokshop.com/doc/page/262796

**Comment by manhhung1511** [comment]
Sorry, I use sanbox app. I call API create product. And it's required. Can you tell me where is wrong?

**Comment by manhhung1511** [comment]
Can you demo help me pass parameters to create products? Thank you very much

**Comment by nVuln** [comment]
@manhhung1511 did you tried api `Product`->`Get Attributes` ?

**Comment by manhhung1511** [comment]
@nVuln Help me!

**Comment by nVuln** [comment]
> @nVuln Help me!

I don't know why you unable to find `product attributes` with `attribute_type = 2 /* SALES_PROPERTY */`
I just picked random category multiple time and get `attributes` of that category and it's always give me attributes with `attribute_type = 2`
also filled that attributes id / custom value to product data and creation successfully

PR #4 resolved this issue so I'll close it
if you need more help please create new issue with more detail, your sample code, error response ...etc...

**Comment by febrihidayan** [comment]
@nVuln have seen a webhook update that requires the shop_id param?
