### ISSUE TITLE
Create product with parameter error

### ISSUE THREAD

**Issue by manhhung1511** [nVuln/tiktokshop-php#6]
Hi, I hope everyone supports me. I use sanbox app.
That attribute is optional. But when i callback it is required to have parameter. 
![image](https://user-images.githubusercontent.com/77888841/206660739-29ace166-4dda-4cf8-9898-add1c76f49db.png)

---
I try call api Product->Get Attributes
![Ảnh 1](https://user-images.githubusercontent.com/77888841/206661084-e193b525-9fc7-42b7-a763-e4f41b920c4d.png)
with attribute_type = 2 /* SALES_PROPERTY */,
with attribute_id = id, attribute_name = name.

But still error

![image](https://user-images.githubusercontent.com/77888841/206661642-6508a54e-c33e-46d0-a80f-979c96a4308d.png)

Hope everyone can help. Thank you very much!

**Comment by nVuln** [comment]
you need fill column `attribute_id` and `custom_value`

**Comment by manhhung1511** [comment]
Thank you very much. I fixed the error
